# Generated by Django 2.0.5 on 2018-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MNIST',
            fields=[
                ('data_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=50)),
                ('label', models.IntegerField(default=0)),
            ],
        ),
    ]
