# Generated by Django 2.0.5 on 2018-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('path', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=20)),
            ],
        ),
    ]
